version: '3.8'

services:
  apigateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "5050:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - authservice
      - espacioservice
      - sedesservice
    networks:
      - app-network

  authservice:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network
  
  espacioservice:
    build:
      context: ./EspacioService
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network
  
  sedesservice:
    build:
      context: ./SedesService
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
